sudo: required
dist: trusty

language: cpp

env:
  DOCKER_COMPOSE_VERSION: 1.11.1

install:
  # Update docker-engine using Ubuntu 'trusty' apt repo
  - curl -sSL "https://get.docker.com/gpg" | sudo -E apt-key add -
  - echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -q
  - sudo apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - docker --version
  
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - docker-compose --version

  # Setup your application stack. You may need to tweak these commands if you
  # doing out-of-the-ordinary docker-compose builds.
  - docker-compose pull
  - docker-compose build
  - docker-compose start
  - docker ps
  
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages: 
            - g++-4.9
            - cmake
            - cmake-data
      env: COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages: 
            - g++-5
            - cmake
            - cmake-data
      env: COMPILER=g++-5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - george-edison55-precise-backports
          packages: 
            - clang-3.6
            - cmake
            - cmake-data
      env: COMPILER=clang++-3.6
      
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - george-edison55-precise-backports
          packages: 
            - clang-3.7
            - cmake
            - cmake-data
      env: COMPILER=clang++-3.7
      
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
            - george-edison55-precise-backports
          packages: 
            - clang-3.8
            - cmake
            - cmake-data
      env: COMPILER=clang++-3.8

branches:
  only:
    - master

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install libssl-dev

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Release -j4 ..
  - make -j4
