language: cpp

sudo: required

os:
  - linux

addons:
  apt:
    packages:
      - clang-3.6
      - clang-3.7
      - clang-3.8
      - clang-3.9

compiler:
  clang:
    - 3.6
    - 3.7
    - 3.8
    - 3.9

std:
  - c++11
  - c++14

branches:
  only:
    - master

before_install:
  - sudo apt-get install cmake

install:
  - $CXX --version
  - which $CXX
  - ./build.sh
