language: cpp

sudo: required

os:
  - linux

compiler:
  clang:
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - 3.9
  gcc:
    - 4.9
    - 5.0
    - 6.0

branches:
  only:
    - master

before_install:
  - sudo apt-get install cmake

install:
  - ./build.sh
