dist: trusty
language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install cmake
  - sudo apt-get install libssl-dev

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      #- libboost-all-dev
      - clang-5.0
      - g++-6

script:
  - pwd
  - uname -a
  - build.sh
  
