language: cpp

sudo: required

os:
  - linux

compiler:
  clang:
    - 3.7
    - 3.8
    - 3.9

std:
  - c++11
  - c++14

branches:
  only:
    - master

before_install:
  - sudo apt-get install cmake

install:
  - $CXX --version
  - which $CXX
  - ./build.sh
